const ProductData = [{"title":"Wicked Lady, The","description":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.","price":55,"inventory":"18-322-8249","imageUrl":"http://dummyimage.com/101x173.png/5fa2dd/ffffff"},
{"title":"Autumn Tale, An (Conte d'automne)","description":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.","price":28,"inventory":"34-017-5576","imageUrl":"http://dummyimage.com/224x237.bmp/5fa2dd/ffffff"},
{"title":"See Heaven","description":"Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.","price":90,"inventory":"90-479-6058","imageUrl":"http://dummyimage.com/168x165.bmp/cc0000/ffffff"},
{"title":"Good Man in Africa, A","description":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","price":79,"inventory":"05-777-0083","imageUrl":"http://dummyimage.com/188x226.jpg/5fa2dd/ffffff"},
{"title":"Premature Burial, The","description":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","price":89,"inventory":"07-473-0419","imageUrl":"http://dummyimage.com/244x226.png/dddddd/000000"},
{"title":"Place of One's Own, A","description":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","price":17,"inventory":"82-622-6605","imageUrl":"http://dummyimage.com/226x180.png/dddddd/000000"},
{"title":"Four Musketeers, The","description":"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.","price":10,"inventory":"22-553-4079","imageUrl":"http://dummyimage.com/116x211.png/cc0000/ffffff"},
{"title":"Sharktopus","description":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","price":31,"inventory":"87-560-6941","imageUrl":"http://dummyimage.com/100x161.jpg/ff4444/ffffff"},
{"title":"Wolf","description":"Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","price":82,"inventory":"85-328-3873","imageUrl":"http://dummyimage.com/178x163.jpg/cc0000/ffffff"},
{"title":"Made in Heaven","description":"Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.","price":41,"inventory":"94-653-2372","imageUrl":"http://dummyimage.com/211x106.bmp/5fa2dd/ffffff"}]

module.export = ProductData